version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/toolbox/fdc3-workbench/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "@types/node"