name: Node.js CI Build and Test

# Controls when the workflow will run on any branch
on:
  pull_request:

# Define the jobs for this workflow
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Run tests
      run: npm run test
      # Tests sometimes hang, and will run until stopped. Timeout to prevent all the minutes from being eaten.
      timeout-minutes: 5

    - name: Generate report
      run: npm run report

    - name: Top level file and folder list?
      run: ls ${{ github.workspace }}

    - name: Read file contents
      uses: guibranco/github-file-reader-action-v2@latest
      id: read_file
      with:
        path: "${{ github.workspace }}/nyc-coverage-report/coverage-summary.json"

    - name: Output file contents
      run: echo "${ steps.read_file.outputs.contents }"

    - name: Post the coverage summary as a comment
      uses: sidx1024/report-nyc-coverage-github-action@v1.2.7
      with:
        coverage_file: "nyc-coverage-report/coverage-summary.json"
